[versions]
runtask = "2.3.0"

# velocity subproject
velocity = "3.2.0-SNAPSHOT"

[plugins]
runtask-velocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
runtask-paper = { id = "xyz.jpenilla.run-paper", version.ref = "runtask" }

[libraries]
# velocity subproject
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
