name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-24.04
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Build plugin
        run: ./gradlew build --no-daemon

      - name: Upload plugin jars
        uses: actions/upload-artifact@v4
        with:
          name: CloudUtilities-Artifacts
          path: build/libs/CloudUtilities-*
          if-no-files-found: error
